/**
 * Square Connect API
 * Client library for accessing the Square Connect APIs
 *
 * OpenAPI spec version: 2.0
 * Contact: developers@squareup.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.3.0-SNAPSHOT
 *
 */
var ApiClient = require('../ApiClient');


/**
 * Enum class BusinessAppointmentSettingsMaxAppointmentsPerDayLimitType.
 * @enum {}
 * @readonly
 */
var exports = {
  /**
   * value: "PER_TEAM_MEMBER"
   * @const
   */
  "TEAM_MEMBER": "PER_TEAM_MEMBER",
  /**
   * value: "PER_LOCATION"
   * @const
   */
  "LOCATION": "PER_LOCATION"};

/**
 * Returns a <code>BusinessAppointmentSettingsMaxAppointmentsPerDayLimitType</code> enum value from a Javascript object name.
 * @param {Object} data The plain JavaScript object containing the name of the enum value.
 * @return {module:model/BusinessAppointmentSettingsMaxAppointmentsPerDayLimitType} The enum <code>BusinessAppointmentSettingsMaxAppointmentsPerDayLimitType</code> value.
 */
exports.constructFromObject = function(object) {
  return object;
}

module.exports = exports;


