/**
 * Square Connect API
 * Client library for accessing the Square Connect APIs
 *
 * OpenAPI spec version: 2.0
 * Contact: developers@squareup.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.3.0-SNAPSHOT
 *
 */
var ApiClient = require('../ApiClient');


/**
 * Enum class CardSquareProduct.
 * @enum {}
 * @readonly
 */
var exports = {
  /**
   * value: "UNKNOWN_SQUARE_PRODUCT"
   * @const
   */
  "UNKNOWN_SQUARE_PRODUCT": "UNKNOWN_SQUARE_PRODUCT",
  /**
   * value: "CONNECT_API"
   * @const
   */
  "CONNECT_API": "CONNECT_API",
  /**
   * value: "DASHBOARD"
   * @const
   */
  "DASHBOARD": "DASHBOARD",
  /**
   * value: "REGISTER_CLIENT"
   * @const
   */
  "REGISTER_CLIENT": "REGISTER_CLIENT",
  /**
   * value: "BUYER_DASHBOARD"
   * @const
   */
  "BUYER_DASHBOARD": "BUYER_DASHBOARD",
  /**
   * value: "WEB"
   * @const
   */
  "WEB": "WEB",
  /**
   * value: "INVOICES"
   * @const
   */
  "INVOICES": "INVOICES",
  /**
   * value: "GIFT_CARD"
   * @const
   */
  "GIFT_CARD": "GIFT_CARD",
  /**
   * value: "VIRTUAL_TERMINAL"
   * @const
   */
  "VIRTUAL_TERMINAL": "VIRTUAL_TERMINAL",
  /**
   * value: "READER_SDK"
   * @const
   */
  "READER_SDK": "READER_SDK"};

/**
 * Returns a <code>CardSquareProduct</code> enum value from a Javascript object name.
 * @param {Object} data The plain JavaScript object containing the name of the enum value.
 * @return {module:model/CardSquareProduct} The enum <code>CardSquareProduct</code> value.
 */
exports.constructFromObject = function(object) {
  return object;
}

module.exports = exports;


