/**
 * Square Connect API
 * Client library for accessing the Square Connect APIs
 *
 * OpenAPI spec version: 2.0
 * Contact: developers@squareup.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.3.0-SNAPSHOT
 *
 */
var ApiClient = require('../ApiClient');


/**
 * Enum class CatalogQuickAmountsSettingsOption.
 * @enum {}
 * @readonly
 */
var exports = {
  /**
   * value: "DISABLED"
   * @const
   */
  "DISABLED": "DISABLED",
  /**
   * value: "MANUAL"
   * @const
   */
  "MANUAL": "MANUAL",
  /**
   * value: "AUTO"
   * @const
   */
  "AUTO": "AUTO"};

/**
 * Returns a <code>CatalogQuickAmountsSettingsOption</code> enum value from a Javascript object name.
 * @param {Object} data The plain JavaScript object containing the name of the enum value.
 * @return {module:model/CatalogQuickAmountsSettingsOption} The enum <code>CatalogQuickAmountsSettingsOption</code> value.
 */
exports.constructFromObject = function(object) {
  return object;
}

module.exports = exports;


