/**
 * Square Connect API
 * Client library for accessing the Square Connect APIs
 *
 * OpenAPI spec version: 2.0
 * Contact: developers@squareup.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.3.0-SNAPSHOT
 *
 */
var ApiClient = require('../ApiClient');


/**
 * Enum class CatalogObjectType.
 * @enum {}
 * @readonly
 */
var exports = {
  /**
   * value: "ITEM"
   * @const
   */
  "ITEM": "ITEM",
  /**
   * value: "IMAGE"
   * @const
   */
  "IMAGE": "IMAGE",
  /**
   * value: "CATEGORY"
   * @const
   */
  "CATEGORY": "CATEGORY",
  /**
   * value: "ITEM_VARIATION"
   * @const
   */
  "ITEM_VARIATION": "ITEM_VARIATION",
  /**
   * value: "TAX"
   * @const
   */
  "TAX": "TAX",
  /**
   * value: "DISCOUNT"
   * @const
   */
  "DISCOUNT": "DISCOUNT",
  /**
   * value: "MODIFIER_LIST"
   * @const
   */
  "MODIFIER_LIST": "MODIFIER_LIST",
  /**
   * value: "MODIFIER"
   * @const
   */
  "MODIFIER": "MODIFIER"};

/**
 * Returns a <code>CatalogObjectType</code> enum value from a Javascript object name.
 * @param {Object} data The plain JavaScript object containing the name of the enum value.
 * @return {module:model/CatalogObjectType} The enum <code>CatalogObjectType</code> value.
 */
exports.constructFromObject = function(object) {
  return object;
}

module.exports = exports;


