/**
 * Square Connect API
 * Client library for accessing the Square Connect APIs
 *
 * OpenAPI spec version: 2.0
 * Contact: developers@squareup.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.3.0-SNAPSHOT
 *
 */
var ApiClient = require('../ApiClient');
var BankAccount = require('./BankAccount');
var Error = require('./Error');




/**
 * The GetBankAccountByV1IdResponse model module.
 * @module model/GetBankAccountByV1IdResponse
 */

/**
 * Constructs a new <code>GetBankAccountByV1IdResponse</code>.
 * Response object returned by GetBankAccountByV1Id.
 * @alias module:model/GetBankAccountByV1IdResponse
 * @class
 */
var exports = function() {
  var _this = this;



};

/**
 * Constructs a <code>GetBankAccountByV1IdResponse</code> from a plain JavaScript object, optionally creating a new instance.
 * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
 * @param {Object} data The plain JavaScript object bearing properties of interest.
 * @param {module:model/GetBankAccountByV1IdResponse} obj Optional instance to populate.
 * @return {module:model/GetBankAccountByV1IdResponse} The populated <code>GetBankAccountByV1IdResponse</code> instance.
 */
exports.constructFromObject = function(data, obj) {
  if (data) {
    obj = obj || new exports();

      if (data.hasOwnProperty('errors')) {
      obj['errors'] = ApiClient.convertToType(data['errors'], [Error]);
    }
      if (data.hasOwnProperty('bank_account')) {
      obj['bank_account'] = BankAccount.constructFromObject(data['bank_account']);
    }
    }
  return obj;
}

/**
 * Information on errors encountered during the request.
 * @member {Array.<module:model/Error>} errors
 */
exports.prototype['errors'] = undefined;
/**
 * The requested `BankAccount` object.
 * @member {module:model/BankAccount} bank_account
 */
exports.prototype['bank_account'] = undefined;



module.exports = exports;



