/**
 * Square Connect API
 * Client library for accessing the Square Connect APIs
 *
 * OpenAPI spec version: 2.0
 * Contact: developers@squareup.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.3.0-SNAPSHOT
 *
 */
var ApiClient = require('../ApiClient');




/**
 * The GetTeamMemberWageRequest model module.
 * @module model/GetTeamMemberWageRequest
 */

/**
 * Constructs a new <code>GetTeamMemberWageRequest</code>.
 * A request to get an &#x60;TeamMemberWage&#x60;
 * @alias module:model/GetTeamMemberWageRequest
 * @class
 */
var exports = function() {
  var _this = this;

};

/**
 * Constructs a <code>GetTeamMemberWageRequest</code> from a plain JavaScript object, optionally creating a new instance.
 * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
 * @param {Object} data The plain JavaScript object bearing properties of interest.
 * @param {module:model/GetTeamMemberWageRequest} obj Optional instance to populate.
 * @return {module:model/GetTeamMemberWageRequest} The populated <code>GetTeamMemberWageRequest</code> instance.
 */
exports.constructFromObject = function(data, obj) {
  if (data) {
    obj = obj || new exports();

    }
  return obj;
}




module.exports = exports;



