/**
 * Square Connect API
 * Client library for accessing the Square Connect APIs
 *
 * OpenAPI spec version: 2.0
 * Contact: developers@squareup.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.3.0-SNAPSHOT
 *
 */
var ApiClient = require('../ApiClient');
var Error = require('./Error');
var TerminalRefund = require('./TerminalRefund');




/**
 * The GetTerminalRefundResponse model module.
 * Note: This model is in beta.
 * @module model/GetTerminalRefundResponse
 */

/**
 * Constructs a new <code>GetTerminalRefundResponse</code>.
 * 
 * @alias module:model/GetTerminalRefundResponse
 * @class
 */
var exports = function() {
  var _this = this;



};

/**
 * Constructs a <code>GetTerminalRefundResponse</code> from a plain JavaScript object, optionally creating a new instance.
 * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
 * @param {Object} data The plain JavaScript object bearing properties of interest.
 * @param {module:model/GetTerminalRefundResponse} obj Optional instance to populate.
 * @return {module:model/GetTerminalRefundResponse} The populated <code>GetTerminalRefundResponse</code> instance.
 */
exports.constructFromObject = function(data, obj) {
  if (data) {
    obj = obj || new exports();

      if (data.hasOwnProperty('errors')) {
      obj['errors'] = ApiClient.convertToType(data['errors'], [Error]);
    }
      if (data.hasOwnProperty('refund')) {
      obj['refund'] = TerminalRefund.constructFromObject(data['refund']);
    }
    }
  return obj;
}

/**
 * Information on errors encountered during the request.
 * @member {Array.<module:model/Error>} errors
 */
exports.prototype['errors'] = undefined;
/**
 * The requested `Refund`
 * @member {module:model/TerminalRefund} refund
 */
exports.prototype['refund'] = undefined;



module.exports = exports;



