/**
 * Square Connect API
 * Client library for accessing the Square Connect APIs
 *
 * OpenAPI spec version: 2.0
 * Contact: developers@squareup.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.3.0-SNAPSHOT
 *
 */
var ApiClient = require('../ApiClient');


/**
 * Enum class OrderServiceChargeCalculationPhase.
 * @enum {}
 * @readonly
 */
var exports = {
  /**
   * value: "SUBTOTAL_PHASE"
   * @const
   */
  "SUBTOTAL_PHASE": "SUBTOTAL_PHASE",
  /**
   * value: "TOTAL_PHASE"
   * @const
   */
  "TOTAL_PHASE": "TOTAL_PHASE"};

/**
 * Returns a <code>OrderServiceChargeCalculationPhase</code> enum value from a Javascript object name.
 * @param {Object} data The plain JavaScript object containing the name of the enum value.
 * @return {module:model/OrderServiceChargeCalculationPhase} The enum <code>OrderServiceChargeCalculationPhase</code> value.
 */
exports.constructFromObject = function(object) {
  return object;
}

module.exports = exports;


