/**
 * Square Connect API
 * Client library for accessing the Square Connect APIs
 *
 * OpenAPI spec version: 2.0
 * Contact: developers@squareup.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.3.0-SNAPSHOT
 *
 */
var ApiClient = require('../ApiClient');
var DisputeEvidence = require('./DisputeEvidence');
var Error = require('./Error');




/**
 * The RetrieveDisputeEvidenceResponse model module.
 * Note: This model is in beta.
 * @module model/RetrieveDisputeEvidenceResponse
 */

/**
 * Constructs a new <code>RetrieveDisputeEvidenceResponse</code>.
 * Defines the fields in a &#x60;RetrieveDisputeEvidence&#x60; response.
 * @alias module:model/RetrieveDisputeEvidenceResponse
 * @class
 */
var exports = function() {
  var _this = this;



};

/**
 * Constructs a <code>RetrieveDisputeEvidenceResponse</code> from a plain JavaScript object, optionally creating a new instance.
 * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
 * @param {Object} data The plain JavaScript object bearing properties of interest.
 * @param {module:model/RetrieveDisputeEvidenceResponse} obj Optional instance to populate.
 * @return {module:model/RetrieveDisputeEvidenceResponse} The populated <code>RetrieveDisputeEvidenceResponse</code> instance.
 */
exports.constructFromObject = function(data, obj) {
  if (data) {
    obj = obj || new exports();

      if (data.hasOwnProperty('errors')) {
      obj['errors'] = ApiClient.convertToType(data['errors'], [Error]);
    }
      if (data.hasOwnProperty('evidence')) {
      obj['evidence'] = DisputeEvidence.constructFromObject(data['evidence']);
    }
    }
  return obj;
}

/**
 * Any errors that occurred during the request.
 * @member {Array.<module:model/Error>} errors
 */
exports.prototype['errors'] = undefined;
/**
 * Metadata about the dispute evidence file.
 * @member {module:model/DisputeEvidence} evidence
 */
exports.prototype['evidence'] = undefined;



module.exports = exports;



