/**
 * Square Connect API
 * Client library for accessing the Square Connect APIs
 *
 * OpenAPI spec version: 2.0
 * Contact: developers@squareup.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.3.0-SNAPSHOT
 *
 */
var ApiClient = require('../ApiClient');




/**
 * The RevokeTokenResponse model module.
 * @module model/RevokeTokenResponse
 */

/**
 * Constructs a new <code>RevokeTokenResponse</code>.
 * 
 * @alias module:model/RevokeTokenResponse
 * @class
 */
var exports = function() {
  var _this = this;


};

/**
 * Constructs a <code>RevokeTokenResponse</code> from a plain JavaScript object, optionally creating a new instance.
 * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
 * @param {Object} data The plain JavaScript object bearing properties of interest.
 * @param {module:model/RevokeTokenResponse} obj Optional instance to populate.
 * @return {module:model/RevokeTokenResponse} The populated <code>RevokeTokenResponse</code> instance.
 */
exports.constructFromObject = function(data, obj) {
  if (data) {
    obj = obj || new exports();

      if (data.hasOwnProperty('success')) {
      obj['success'] = ApiClient.convertToType(data['success'], 'Boolean');
    }
    }
  return obj;
}

/**
 * If the request is successful, this is true.
 * @member {Boolean} success
 */
exports.prototype['success'] = undefined;



module.exports = exports;



