/**
 * Square Connect API
 * Client library for accessing the Square Connect APIs
 *
 * OpenAPI spec version: 2.0
 * Contact: developers@squareup.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.3.0-SNAPSHOT
 *
 */
var ApiClient = require('../ApiClient');




/**
 * The TerminalCheckoutQuerySort model module.
 * @module model/TerminalCheckoutQuerySort
 */

/**
 * Constructs a new <code>TerminalCheckoutQuerySort</code>.
 * 
 * @alias module:model/TerminalCheckoutQuerySort
 * @class
 */
var exports = function() {
  var _this = this;


};

/**
 * Constructs a <code>TerminalCheckoutQuerySort</code> from a plain JavaScript object, optionally creating a new instance.
 * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
 * @param {Object} data The plain JavaScript object bearing properties of interest.
 * @param {module:model/TerminalCheckoutQuerySort} obj Optional instance to populate.
 * @return {module:model/TerminalCheckoutQuerySort} The populated <code>TerminalCheckoutQuerySort</code> instance.
 */
exports.constructFromObject = function(data, obj) {
  if (data) {
    obj = obj || new exports();

      if (data.hasOwnProperty('sort_order')) {
      obj['sort_order'] = ApiClient.convertToType(data['sort_order'], 'String');
    }
    }
  return obj;
}

/**
 * The order in which results are listed. - `ASC` - oldest to newest - `DESC` - newest to oldest (default).
 * @member {String} sort_order
 */
exports.prototype['sort_order'] = undefined;



module.exports = exports;



