/**
 * Square Connect API
 * Client library for accessing the Square Connect APIs
 *
 * OpenAPI spec version: 2.0
 * Contact: developers@squareup.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.3.0-SNAPSHOT
 *
 */
var ApiClient = require('../ApiClient');
var Shift = require('./Shift');




/**
 * The UpdateShiftRequest model module.
 * @module model/UpdateShiftRequest
 */

/**
 * Constructs a new <code>UpdateShiftRequest</code>.
 * A request to update a &#x60;Shift&#x60; object.
 * @alias module:model/UpdateShiftRequest
 * @class
 * @param shift {module:model/Shift} The updated `Shift` object.
 */
var exports = function(shift) {
  var _this = this;

  _this['shift'] = shift;
};

/**
 * Constructs a <code>UpdateShiftRequest</code> from a plain JavaScript object, optionally creating a new instance.
 * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
 * @param {Object} data The plain JavaScript object bearing properties of interest.
 * @param {module:model/UpdateShiftRequest} obj Optional instance to populate.
 * @return {module:model/UpdateShiftRequest} The populated <code>UpdateShiftRequest</code> instance.
 */
exports.constructFromObject = function(data, obj) {
  if (data) {
    obj = obj || new exports();

      if (data.hasOwnProperty('shift')) {
      obj['shift'] = Shift.constructFromObject(data['shift']);
    }
    }
  return obj;
}

/**
 * The updated `Shift` object.
 * @member {module:model/Shift} shift
 */
exports.prototype['shift'] = undefined;



module.exports = exports;



