/**
 * Square Connect API
 * Client library for accessing the Square Connect APIs
 *
 * OpenAPI spec version: 2.0
 * Contact: developers@squareup.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.3.0-SNAPSHOT
 *
 */
var ApiClient = require('../ApiClient');


/**
 * Enum class V1BankAccountType.
 * @enum {}
 * @readonly
 */
var exports = {
  /**
   * value: "BUSINESS_CHECKING"
   * @const
   */
  "BUSINESS_CHECKING": "BUSINESS_CHECKING",
  /**
   * value: "CHECKING"
   * @const
   */
  "CHECKING": "CHECKING",
  /**
   * value: "INVESTMENT"
   * @const
   */
  "INVESTMENT": "INVESTMENT",
  /**
   * value: "LOAN"
   * @const
   */
  "LOAN": "LOAN",
  /**
   * value: "SAVINGS"
   * @const
   */
  "SAVINGS": "SAVINGS",
  /**
   * value: "OTHER"
   * @const
   */
  "OTHER": "OTHER"};

/**
 * Returns a <code>V1BankAccountType</code> enum value from a Javascript object name.
 * @param {Object} data The plain JavaScript object containing the name of the enum value.
 * @return {module:model/V1BankAccountType} The enum <code>V1BankAccountType</code> value.
 */
exports.constructFromObject = function(object) {
  return object;
}

module.exports = exports;


