/**
 * Square Connect API
 * Client library for accessing the Square Connect APIs
 *
 * OpenAPI spec version: 2.0
 * Contact: developers@squareup.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.3.0-SNAPSHOT
 *
 */
var ApiClient = require('../ApiClient');


/**
 * Enum class V1OrderHistoryEntryAction.
 * @enum {}
 * @readonly
 */
var exports = {
  /**
   * value: "ORDER_PLACED"
   * @const
   */
  "ORDER_PLACED": "ORDER_PLACED",
  /**
   * value: "DECLINED"
   * @const
   */
  "DECLINED": "DECLINED",
  /**
   * value: "PAYMENT_RECEIVED"
   * @const
   */
  "PAYMENT_RECEIVED": "PAYMENT_RECEIVED",
  /**
   * value: "CANCELED"
   * @const
   */
  "CANCELED": "CANCELED",
  /**
   * value: "COMPLETED"
   * @const
   */
  "COMPLETED": "COMPLETED",
  /**
   * value: "REFUNDED"
   * @const
   */
  "REFUNDED": "REFUNDED",
  /**
   * value: "EXPIRED"
   * @const
   */
  "EXPIRED": "EXPIRED"};

/**
 * Returns a <code>V1OrderHistoryEntryAction</code> enum value from a Javascript object name.
 * @param {Object} data The plain JavaScript object containing the name of the enum value.
 * @return {module:model/V1OrderHistoryEntryAction} The enum <code>V1OrderHistoryEntryAction</code> value.
 */
exports.constructFromObject = function(object) {
  return object;
}

module.exports = exports;


