/**
 * Square Connect API
 * Client library for accessing the Square Connect APIs
 *
 * OpenAPI spec version: 2.0
 * Contact: developers@squareup.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.3.0-SNAPSHOT
 *
 */
var ApiClient = require('../ApiClient');
var V1Fee = require('./V1Fee');




/**
 * @deprecated
 * The V1UpdateFeeRequest model module.
 * @module model/V1UpdateFeeRequest
 */

/**
 * Constructs a new <code>V1UpdateFeeRequest</code>.
 * 
 * @alias module:model/V1UpdateFeeRequest
 * @class
 * @param body {module:model/V1Fee} An object containing the fields to POST for the request.  See the corresponding object definition for field details.
 */
var exports = function(body) {
  var _this = this;

  _this['body'] = body;
};

/**
 * Constructs a <code>V1UpdateFeeRequest</code> from a plain JavaScript object, optionally creating a new instance.
 * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
 * @param {Object} data The plain JavaScript object bearing properties of interest.
 * @param {module:model/V1UpdateFeeRequest} obj Optional instance to populate.
 * @return {module:model/V1UpdateFeeRequest} The populated <code>V1UpdateFeeRequest</code> instance.
 */
exports.constructFromObject = function(data, obj) {
  if (data) {
    obj = obj || new exports();

      if (data.hasOwnProperty('body')) {
      obj['body'] = V1Fee.constructFromObject(data['body']);
    }
    }
  return obj;
}

/**
 * An object containing the fields to POST for the request.  See the corresponding object definition for field details.
 * @member {module:model/V1Fee} body
 */
exports.prototype['body'] = undefined;



module.exports = exports;



