/**
 * Square Connect API
 * Client library for accessing the Square Connect APIs
 *
 * OpenAPI spec version: 2.0
 * Contact: developers@squareup.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.3.0-SNAPSHOT
 *
 */
const SquareConnect = require('../../src/index');

describe('BusinessBookingProfile', function() {
  beforeEach(function() {
    this.api = new SquareConnect.BusinessBookingProfile();
  });

  it('should create an instance of BusinessBookingProfile', function() {
    // uncomment below and update the code to test BusinessBookingProfile
    //var instane = new SquareConnect.BusinessBookingProfile();
    //expect(instance).to.be.a(SquareConnect.BusinessBookingProfile);
  });

  it('should have the property sellerId (base name: "seller_id")', function() {
    // uncomment below and update the code to test the property sellerId
    //var instane = new SquareConnect.BusinessBookingProfile();
    //expect(instance).to.be();
  });
  it('should have the property createdAt (base name: "created_at")', function() {
    // uncomment below and update the code to test the property createdAt
    //var instane = new SquareConnect.BusinessBookingProfile();
    //expect(instance).to.be();
  });
  it('should have the property bookingEnabled (base name: "booking_enabled")', function() {
    // uncomment below and update the code to test the property bookingEnabled
    //var instane = new SquareConnect.BusinessBookingProfile();
    //expect(instance).to.be();
  });
  it('should have the property customerTimezoneChoice (base name: "customer_timezone_choice")', function() {
    // uncomment below and update the code to test the property customerTimezoneChoice
    //var instane = new SquareConnect.BusinessBookingProfile();
    //expect(instance).to.be();
  });
  it('should have the property bookingPolicy (base name: "booking_policy")', function() {
    // uncomment below and update the code to test the property bookingPolicy
    //var instane = new SquareConnect.BusinessBookingProfile();
    //expect(instance).to.be();
  });
  it('should have the property allowUserCancel (base name: "allow_user_cancel")', function() {
    // uncomment below and update the code to test the property allowUserCancel
    //var instane = new SquareConnect.BusinessBookingProfile();
    //expect(instance).to.be();
  });
  it('should have the property businessAppointmentSettings (base name: "business_appointment_settings")', function() {
    // uncomment below and update the code to test the property businessAppointmentSettings
    //var instane = new SquareConnect.BusinessBookingProfile();
    //expect(instance).to.be();
  });
});
