/**
 * Square Connect API
 * Client library for accessing the Square Connect APIs
 *
 * OpenAPI spec version: 2.0
 * Contact: developers@squareup.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.3.0-SNAPSHOT
 *
 */
const SquareConnect = require('../../src/index');

describe('CalculateOrderResponse', function() {
  beforeEach(function() {
    this.api = new SquareConnect.CalculateOrderResponse();
  });

  it('should create an instance of CalculateOrderResponse', function() {
    // uncomment below and update the code to test CalculateOrderResponse
    //var instane = new SquareConnect.CalculateOrderResponse();
    //expect(instance).to.be.a(SquareConnect.CalculateOrderResponse);
  });

  it('should have the property order (base name: "order")', function() {
    // uncomment below and update the code to test the property order
    //var instane = new SquareConnect.CalculateOrderResponse();
    //expect(instance).to.be();
  });
  it('should have the property errors (base name: "errors")', function() {
    // uncomment below and update the code to test the property errors
    //var instane = new SquareConnect.CalculateOrderResponse();
    //expect(instance).to.be();
  });
});
