/**
 * Square Connect API
 * Client library for accessing the Square Connect APIs
 *
 * OpenAPI spec version: 2.0
 * Contact: developers@squareup.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.3.0-SNAPSHOT
 *
 */
const SquareConnect = require('../../src/index');

describe('CancelTerminalRefundResponse', function() {
  beforeEach(function() {
    this.api = new SquareConnect.CancelTerminalRefundResponse();
  });

  it('should create an instance of CancelTerminalRefundResponse', function() {
    // uncomment below and update the code to test CancelTerminalRefundResponse
    //var instane = new SquareConnect.CancelTerminalRefundResponse();
    //expect(instance).to.be.a(SquareConnect.CancelTerminalRefundResponse);
  });

  it('should have the property errors (base name: "errors")', function() {
    // uncomment below and update the code to test the property errors
    //var instane = new SquareConnect.CancelTerminalRefundResponse();
    //expect(instance).to.be();
  });
  it('should have the property refund (base name: "refund")', function() {
    // uncomment below and update the code to test the property refund
    //var instane = new SquareConnect.CancelTerminalRefundResponse();
    //expect(instance).to.be();
  });
});
