/**
 * Square Connect API
 * Client library for accessing the Square Connect APIs
 *
 * OpenAPI spec version: 2.0
 * Contact: developers@squareup.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.3.0-SNAPSHOT
 *
 */
const SquareConnect = require('../../src/index');

describe('CancelSubscriptionResponse', function() {
  beforeEach(function() {
    this.api = new SquareConnect.CancelSubscriptionResponse();
  });

  it('should create an instance of CancelSubscriptionResponse', function() {
    // uncomment below and update the code to test CancelSubscriptionResponse
    //var instane = new SquareConnect.CancelSubscriptionResponse();
    //expect(instance).to.be.a(SquareConnect.CancelSubscriptionResponse);
  });

  it('should have the property errors (base name: "errors")', function() {
    // uncomment below and update the code to test the property errors
    //var instane = new SquareConnect.CancelSubscriptionResponse();
    //expect(instance).to.be();
  });
  it('should have the property subscription (base name: "subscription")', function() {
    // uncomment below and update the code to test the property subscription
    //var instane = new SquareConnect.CancelSubscriptionResponse();
    //expect(instance).to.be();
  });
});
