/**
 * Square Connect API
 * Client library for accessing the Square Connect APIs
 *
 * OpenAPI spec version: 2.0
 * Contact: developers@squareup.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.20191217.0-SNAPSHOT
 *
 */
const SquareConnect = require('../../src/index');

describe('CashDrawerShift', function() {
  beforeEach(function() {
    this.api = new SquareConnect.CashDrawerShift();
  });

  it('should create an instance of CashDrawerShift', function() {
    // uncomment below and update the code to test CashDrawerShift
    //var instane = new SquareConnect.CashDrawerShift();
    //expect(instance).to.be.a(SquareConnect.CashDrawerShift);
  });

  it('should have the property id (base name: "id")', function() {
    // uncomment below and update the code to test the property id
    //var instane = new SquareConnect.CashDrawerShift();
    //expect(instance).to.be();
  });
  it('should have the property state (base name: "state")', function() {
    // uncomment below and update the code to test the property state
    //var instane = new SquareConnect.CashDrawerShift();
    //expect(instance).to.be();
  });
  it('should have the property openedAt (base name: "opened_at")', function() {
    // uncomment below and update the code to test the property openedAt
    //var instane = new SquareConnect.CashDrawerShift();
    //expect(instance).to.be();
  });
  it('should have the property endedAt (base name: "ended_at")', function() {
    // uncomment below and update the code to test the property endedAt
    //var instane = new SquareConnect.CashDrawerShift();
    //expect(instance).to.be();
  });
  it('should have the property closedAt (base name: "closed_at")', function() {
    // uncomment below and update the code to test the property closedAt
    //var instane = new SquareConnect.CashDrawerShift();
    //expect(instance).to.be();
  });
  it('should have the property employeeIds (base name: "employee_ids")', function() {
    // uncomment below and update the code to test the property employeeIds
    //var instane = new SquareConnect.CashDrawerShift();
    //expect(instance).to.be();
  });
  it('should have the property openingEmployeeId (base name: "opening_employee_id")', function() {
    // uncomment below and update the code to test the property openingEmployeeId
    //var instane = new SquareConnect.CashDrawerShift();
    //expect(instance).to.be();
  });
  it('should have the property endingEmployeeId (base name: "ending_employee_id")', function() {
    // uncomment below and update the code to test the property endingEmployeeId
    //var instane = new SquareConnect.CashDrawerShift();
    //expect(instance).to.be();
  });
  it('should have the property closingEmployeeId (base name: "closing_employee_id")', function() {
    // uncomment below and update the code to test the property closingEmployeeId
    //var instane = new SquareConnect.CashDrawerShift();
    //expect(instance).to.be();
  });
  it('should have the property description (base name: "description")', function() {
    // uncomment below and update the code to test the property description
    //var instane = new SquareConnect.CashDrawerShift();
    //expect(instance).to.be();
  });
  it('should have the property openedCashMoney (base name: "opened_cash_money")', function() {
    // uncomment below and update the code to test the property openedCashMoney
    //var instane = new SquareConnect.CashDrawerShift();
    //expect(instance).to.be();
  });
  it('should have the property cashPaymentMoney (base name: "cash_payment_money")', function() {
    // uncomment below and update the code to test the property cashPaymentMoney
    //var instane = new SquareConnect.CashDrawerShift();
    //expect(instance).to.be();
  });
  it('should have the property cashRefundsMoney (base name: "cash_refunds_money")', function() {
    // uncomment below and update the code to test the property cashRefundsMoney
    //var instane = new SquareConnect.CashDrawerShift();
    //expect(instance).to.be();
  });
  it('should have the property cashPaidInMoney (base name: "cash_paid_in_money")', function() {
    // uncomment below and update the code to test the property cashPaidInMoney
    //var instane = new SquareConnect.CashDrawerShift();
    //expect(instance).to.be();
  });
  it('should have the property cashPaidOutMoney (base name: "cash_paid_out_money")', function() {
    // uncomment below and update the code to test the property cashPaidOutMoney
    //var instane = new SquareConnect.CashDrawerShift();
    //expect(instance).to.be();
  });
  it('should have the property expectedCashMoney (base name: "expected_cash_money")', function() {
    // uncomment below and update the code to test the property expectedCashMoney
    //var instane = new SquareConnect.CashDrawerShift();
    //expect(instance).to.be();
  });
  it('should have the property closedCashMoney (base name: "closed_cash_money")', function() {
    // uncomment below and update the code to test the property closedCashMoney
    //var instane = new SquareConnect.CashDrawerShift();
    //expect(instance).to.be();
  });
  it('should have the property device (base name: "device")', function() {
    // uncomment below and update the code to test the property device
    //var instane = new SquareConnect.CashDrawerShift();
    //expect(instance).to.be();
  });
});
