/**
 * Square Connect API
 * Client library for accessing the Square Connect APIs
 *
 * OpenAPI spec version: 2.0
 * Contact: developers@squareup.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.3.0-SNAPSHOT
 *
 */
const SquareConnect = require('../../src/index');

describe('CatalogQueryCustomAttributeUsage', function() {
  beforeEach(function() {
//     this.api = new SquareConnect.CatalogQueryCustomAttributeUsage();
  });

  it('should create an instance of CatalogQueryCustomAttributeUsage', function() {
    // uncomment below and update the code to test CatalogQueryCustomAttributeUsage
    //var instane = new SquareConnect.CatalogQueryCustomAttributeUsage();
    //expect(instance).to.be.a(SquareConnect.CatalogQueryCustomAttributeUsage);
  });

  it('should have the property customAttributeDefinitionIds (base name: "custom_attribute_definition_ids")', function() {
    // uncomment below and update the code to test the property customAttributeDefinitionIds
    //var instane = new SquareConnect.CatalogQueryCustomAttributeUsage();
    //expect(instance).to.be();
  });
  it('should have the property hasValue (base name: "has_value")', function() {
    // uncomment below and update the code to test the property hasValue
    //var instane = new SquareConnect.CatalogQueryCustomAttributeUsage();
    //expect(instance).to.be();
  });
});
