/**
 * Square Connect API
 * Client library for accessing the Square Connect APIs
 *
 * OpenAPI spec version: 2.0
 * Contact: developers@squareup.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.3.0-SNAPSHOT
 *
 */
const SquareConnect = require('../../src/index');

describe('CatalogQueryFilteredItemsCustomAttributeFilter', function() {
  beforeEach(function() {
    // this.api = new SquareConnect.CatalogQueryFilteredItemsCustomAttributeFilter();
  });

  it('should create an instance of CatalogQueryFilteredItemsCustomAttributeFilter', function() {
    // uncomment below and update the code to test CatalogQueryFilteredItemsCustomAttributeFilter
    //var instance = new SquareConnect.CatalogQueryFilteredItemsCustomAttributeFilter();
    //expect(instance).to.be.a(SquareConnect.CatalogQueryFilteredItemsCustomAttributeFilter);
  });

  it('should have the property filterType (base name: "filter_type")', function() {
    // uncomment below and update the code to test the property filterType
    //var instance = new SquareConnect.CatalogQueryFilteredItemsCustomAttributeFilter();
    //expect(instance).to.be();
  });
  it('should have the property customAttributeDefinitionIds (base name: "custom_attribute_definition_ids")', function() {
    // uncomment below and update the code to test the property customAttributeDefinitionIds
    //var instance = new SquareConnect.CatalogQueryFilteredItemsCustomAttributeFilter();
    //expect(instance).to.be();
  });
  it('should have the property customAttributeValueExact (base name: "custom_attribute_value_exact")', function() {
    // uncomment below and update the code to test the property customAttributeValueExact
    //var instance = new SquareConnect.CatalogQueryFilteredItemsCustomAttributeFilter();
    //expect(instance).to.be();
  });
  it('should have the property customAttributeValuePrefix (base name: "custom_attribute_value_prefix")', function() {
    // uncomment below and update the code to test the property customAttributeValuePrefix
    //var instance = new SquareConnect.CatalogQueryFilteredItemsCustomAttributeFilter();
    //expect(instance).to.be();
  });
  it('should have the property customAttributeMinValue (base name: "custom_attribute_min_value")', function() {
    // uncomment below and update the code to test the property customAttributeMinValue
    //var instance = new SquareConnect.CatalogQueryFilteredItemsCustomAttributeFilter();
    //expect(instance).to.be();
  });
  it('should have the property customAttributeMaxValue (base name: "custom_attribute_max_value")', function() {
    // uncomment below and update the code to test the property customAttributeMaxValue
    //var instance = new SquareConnect.CatalogQueryFilteredItemsCustomAttributeFilter();
    //expect(instance).to.be();
  });
});
