/**
 * Square Connect API
 * Client library for accessing the Square Connect APIs
 *
 * OpenAPI spec version: 2.0
 * Contact: developers@squareup.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.3.0-SNAPSHOT
 *
 */

const SquareConnect = require('../../src/index');

describe('CatalogObjectBatch', function() {
  beforeEach(function() {
    this.api = new SquareConnect.CatalogObjectBatch();
  });

  it('should create an instance of CatalogObjectBatch', function() {
    // uncomment below and update the code to test CatalogObjectBatch
    //var instance = new SquareConnect.CatalogObjectBatch();
    //expect(instance).to.be.a(SquareConnect.CatalogObjectBatch);
  });

  it('should have the property objects (base name: "objects")', function() {
    // uncomment below and update the code to test the property objects
    //var instance = new SquareConnect.CatalogObjectBatch();
    //expect(instance).to.be();
  });
});

