/**
 * Square Connect API
 * Client library for accessing the Square Connect APIs
 *
 * OpenAPI spec version: 2.0
 * Contact: developers@squareup.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.3.0-SNAPSHOT
 *
 */

const SquareConnect = require('../../src/index');

describe('CatalogDiscountType', function() {
  beforeEach(function() {
  });

  it('should create an instance of CatalogDiscountType', function() {
    // uncomment below and update the code to test CatalogDiscountType
    //var instane = new SquareConnect.CatalogDiscountType();
    //expect(instance).to.be.a(SquareConnect.CatalogDiscountType);
  });

});

