/**
 * Square Connect API
 * Client library for accessing the Square Connect APIs
 *
 * OpenAPI spec version: 2.0
 * Contact: developers@squareup.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.3.0-SNAPSHOT
 *
 */

const SquareConnect = require('../../src/index');

describe('ChargeRequestAdditionalRecipient', function() {
  beforeEach(function() {
    this.api = new SquareConnect.ChargeRequestAdditionalRecipient();
  });

  it('should create an instance of ChargeRequestAdditionalRecipient', function() {
    // uncomment below and update the code to test ChargeRequestAdditionalRecipient
    //var instance = new SquareConnect.ChargeRequestAdditionalRecipient();
    //expect(instance).to.be.a(SquareConnect.ChargeRequestAdditionalRecipient);
  });

  it('should have the property locationId (base name: "location_id")', function() {
    // uncomment below and update the code to test the property locationId
    //var instance = new SquareConnect.ChargeRequestAdditionalRecipient();
    //expect(instance).to.be();
  });
  it('should have the property description (base name: "description")', function() {
    // uncomment below and update the code to test the property description
    //var instance = new SquareConnect.ChargeRequestAdditionalRecipient();
    //expect(instance).to.be();
  });
  it('should have the property amountMoney (base name: "amount_money")', function() {
    // uncomment below and update the code to test the property amountMoney
    //var instance = new SquareConnect.ChargeRequestAdditionalRecipient();
    //expect(instance).to.be();
  });
});

