/**
 * Square Connect API
 * Client library for accessing the Square Connect APIs
 *
 * OpenAPI spec version: 2.0
 * Contact: developers@squareup.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.3.0-SNAPSHOT
 *
 */
const SquareConnect = require('../../src/index');

describe('CreateCatalogImageRequest', function() {
  beforeEach(function() {
    this.api = new SquareConnect.CreateCatalogImageRequest();
  });

  it('should create an instance of CreateCatalogImageRequest', function() {
    // uncomment below and update the code to test CreateCatalogImageRequest
    //var instance = new SquareConnect.CreateCatalogImageRequest();
    //expect(instance).to.be.a(SquareConnect.CreateCatalogImageRequest);
  });

  it('should have the property idempotencyKey (base name: "idempotency_key")', function() {
    // uncomment below and update the code to test the property idempotencyKey
    //var instance = new SquareConnect.CreateCatalogImageRequest();
    //expect(instance).to.be();
  });
  it('should have the property objectId (base name: "object_id")', function() {
    // uncomment below and update the code to test the property objectId
    //var instance = new SquareConnect.CreateCatalogImageRequest();
    //expect(instance).to.be();
  });
  it('should have the property image (base name: "image")', function() {
    // uncomment below and update the code to test the property image
    //var instance = new SquareConnect.CreateCatalogImageRequest();
    //expect(instance).to.be();
  });
});
