/**
 * Square Connect API
 * Client library for accessing the Square Connect APIs
 *
 * OpenAPI spec version: 2.0
 * Contact: developers@squareup.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.3.0-SNAPSHOT
 *
 */
const SquareConnect = require('../../src/index');

describe('CreateCustomerGroupRequest', function() {
  beforeEach(function() {
    this.api = new SquareConnect.CreateCustomerGroupRequest();
  });

  it('should create an instance of CreateCustomerGroupRequest', function() {
    // uncomment below and update the code to test CreateCustomerGroupRequest
    //var instane = new SquareConnect.CreateCustomerGroupRequest();
    //expect(instance).to.be.a(SquareConnect.CreateCustomerGroupRequest);
  });

  it('should have the property idempotencyKey (base name: "idempotency_key")', function() {
    // uncomment below and update the code to test the property idempotencyKey
    //var instane = new SquareConnect.CreateCustomerGroupRequest();
    //expect(instance).to.be();
  });
  it('should have the property group (base name: "group")', function() {
    // uncomment below and update the code to test the property group
    //var instane = new SquareConnect.CreateCustomerGroupRequest();
    //expect(instance).to.be();
  });
});
