/**
 * Square Connect API
 * Client library for accessing the Square Connect APIs
 *
 * OpenAPI spec version: 2.0
 * Contact: developers@squareup.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.20191217.0-SNAPSHOT
 *
 */

const SquareConnect = require('../../src/index');

describe('CreateOrderRequestLineItem', function() {
  beforeEach(function() {
    this.api = new SquareConnect.CreateOrderRequestLineItem();
  });

  it('should create an instance of CreateOrderRequestLineItem', function() {
    // uncomment below and update the code to test CreateOrderRequestLineItem
    //var instane = new SquareConnect.CreateOrderRequestLineItem();
    //expect(instance).to.be.a(SquareConnect.CreateOrderRequestLineItem);
  });

  it('should have the property name (base name: "name")', function() {
    // uncomment below and update the code to test the property name
    //var instane = new SquareConnect.CreateOrderRequestLineItem();
    //expect(instance).to.be();
  });
  it('should have the property quantity (base name: "quantity")', function() {
    // uncomment below and update the code to test the property quantity
    //var instane = new SquareConnect.CreateOrderRequestLineItem();
    //expect(instance).to.be();
  });
  it('should have the property basePriceMoney (base name: "base_price_money")', function() {
    // uncomment below and update the code to test the property basePriceMoney
    //var instane = new SquareConnect.CreateOrderRequestLineItem();
    //expect(instance).to.be();
  });
  it('should have the property variationName (base name: "variation_name")', function() {
    // uncomment below and update the code to test the property variationName
    //var instane = new SquareConnect.CreateOrderRequestLineItem();
    //expect(instance).to.be();
  });
  it('should have the property note (base name: "note")', function() {
    // uncomment below and update the code to test the property note
    //var instane = new SquareConnect.CreateOrderRequestLineItem();
    //expect(instance).to.be();
  });
  it('should have the property catalogObjectId (base name: "catalog_object_id")', function() {
    // uncomment below and update the code to test the property catalogObjectId
    //var instane = new SquareConnect.CreateOrderRequestLineItem();
    //expect(instance).to.be();
  });
  it('should have the property modifiers (base name: "modifiers")', function() {
    // uncomment below and update the code to test the property modifiers
    //var instane = new SquareConnect.CreateOrderRequestLineItem();
    //expect(instance).to.be();
  });
  it('should have the property taxes (base name: "taxes")', function() {
    // uncomment below and update the code to test the property taxes
    //var instane = new SquareConnect.CreateOrderRequestLineItem();
    //expect(instance).to.be();
  });
  it('should have the property discounts (base name: "discounts")', function() {
    // uncomment below and update the code to test the property discounts
    //var instane = new SquareConnect.CreateOrderRequestLineItem();
    //expect(instance).to.be();
  });
});

