/**
 * Square Connect API
 * Client library for accessing the Square Connect APIs
 *
 * OpenAPI spec version: 2.0
 * Contact: developers@squareup.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.3.0-SNAPSHOT
 *
 */
const SquareConnect = require('../../src/index');

describe('CreateDisputeEvidenceTextRequest', function() {
  beforeEach(function() {
    this.api = new SquareConnect.CreateDisputeEvidenceTextRequest();
  });

  it('should create an instance of CreateDisputeEvidenceTextRequest', function() {
    // uncomment below and update the code to test CreateDisputeEvidenceTextRequest
    //var instane = new SquareConnect.CreateDisputeEvidenceTextRequest();
    //expect(instance).to.be.a(SquareConnect.CreateDisputeEvidenceTextRequest);
  });

  it('should have the property idempotencyKey (base name: "idempotency_key")', function() {
    // uncomment below and update the code to test the property idempotencyKey
    //var instane = new SquareConnect.CreateDisputeEvidenceTextRequest();
    //expect(instance).to.be();
  });
  it('should have the property evidenceType (base name: "evidence_type")', function() {
    // uncomment below and update the code to test the property evidenceType
    //var instane = new SquareConnect.CreateDisputeEvidenceTextRequest();
    //expect(instance).to.be();
  });
  it('should have the property evidenceText (base name: "evidence_text")', function() {
    // uncomment below and update the code to test the property evidenceText
    //var instane = new SquareConnect.CreateDisputeEvidenceTextRequest();
    //expect(instance).to.be();
  });
});
