/**
 * Square Connect API
 * Client library for accessing the Square Connect APIs
 *
 * OpenAPI spec version: 2.0
 * Contact: developers@squareup.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.3.0-SNAPSHOT
 *
 */
const SquareConnect = require('../../src/index');

describe('CustomerFilter', function() {
  beforeEach(function() {
    this.api = new SquareConnect.CustomerFilter();
  });

  it('should create an instance of CustomerFilter', function() {
    // uncomment below and update the code to test CustomerFilter
    //var instane = new SquareConnect.CustomerFilter();
    //expect(instance).to.be.a(SquareConnect.CustomerFilter);
  });

  it('should have the property creationSource (base name: "creation_source")', function() {
    // uncomment below and update the code to test the property creationSource
    //var instane = new SquareConnect.CustomerFilter();
    //expect(instance).to.be();
  });
  it('should have the property createdAt (base name: "created_at")', function() {
    // uncomment below and update the code to test the property createdAt
    //var instane = new SquareConnect.CustomerFilter();
    //expect(instance).to.be();
  });
  it('should have the property updatedAt (base name: "updated_at")', function() {
    // uncomment below and update the code to test the property updatedAt
    //var instane = new SquareConnect.CustomerFilter();
    //expect(instance).to.be();
  });
});
