/**
 * Square Connect API
 * Client library for accessing the Square Connect APIs
 *
 * OpenAPI spec version: 2.0
 * Contact: developers@squareup.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.3.0-SNAPSHOT
 *
 */
const SquareConnect = require('../../src/index');

describe('DisputeEvidence', function() {
  beforeEach(function() {
    this.api = new SquareConnect.DisputeEvidence();
  });

  it('should create an instance of DisputeEvidence', function() {
    // uncomment below and update the code to test DisputeEvidence
    //var instance = new SquareConnect.DisputeEvidence();
    //expect(instance).to.be.a(SquareConnect.DisputeEvidence);
  });

  it('should have the property evidenceId (base name: "evidence_id")', function() {
    // uncomment below and update the code to test the property evidenceId
    //var instance = new SquareConnect.DisputeEvidence();
    //expect(instance).to.be();
  });
  it('should have the property disputeId (base name: "dispute_id")', function() {
    // uncomment below and update the code to test the property disputeId
    //var instance = new SquareConnect.DisputeEvidence();
    //expect(instance).to.be();
  });
  it('should have the property uploadedAt (base name: "uploaded_at")', function() {
    // uncomment below and update the code to test the property uploadedAt
    //var instance = new SquareConnect.DisputeEvidence();
    //expect(instance).to.be();
  });
  it('should have the property evidenceType (base name: "evidence_type")', function() {
    // uncomment below and update the code to test the property evidenceType
    //var instance = new SquareConnect.DisputeEvidence();
    //expect(instance).to.be();
  });
});
