/**
 * Square Connect API
 * Client library for accessing the Square Connect APIs
 *
 * OpenAPI spec version: 2.0
 * Contact: developers@squareup.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.20191217.0-SNAPSHOT
 *
 */
const SquareConnect = require('../../src/index');

describe('ListCashDrawerShiftsResponse', function() {
  beforeEach(function() {
    this.api = new SquareConnect.ListCashDrawerShiftsResponse();
  });

  it('should create an instance of ListCashDrawerShiftsResponse', function() {
    // uncomment below and update the code to test ListCashDrawerShiftsResponse
    //var instane = new SquareConnect.ListCashDrawerShiftsResponse();
    //expect(instance).to.be.a(SquareConnect.ListCashDrawerShiftsResponse);
  });

  it('should have the property items (base name: "items")', function() {
    // uncomment below and update the code to test the property items
    //var instane = new SquareConnect.ListCashDrawerShiftsResponse();
    //expect(instance).to.be();
  });
  it('should have the property cursor (base name: "cursor")', function() {
    // uncomment below and update the code to test the property cursor
    //var instane = new SquareConnect.ListCashDrawerShiftsResponse();
    //expect(instance).to.be();
  });
  it('should have the property errors (base name: "errors")', function() {
    // uncomment below and update the code to test the property errors
    //var instane = new SquareConnect.ListCashDrawerShiftsResponse();
    //expect(instance).to.be();
  });
});
