/**
 * Square Connect API
 * Client library for accessing the Square Connect APIs
 *
 * OpenAPI spec version: 2.0
 * Contact: developers@squareup.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.3.0-SNAPSHOT
 *
 */
const SquareConnect = require('../../src/index');

describe('LoyaltyEventQuery', function() {
  beforeEach(function() {
    this.api = new SquareConnect.LoyaltyEventQuery();
  });

  it('should create an instance of LoyaltyEventQuery', function() {
    // uncomment below and update the code to test LoyaltyEventQuery
    //var instance = new SquareConnect.LoyaltyEventQuery();
    //expect(instance).to.be.a(SquareConnect.LoyaltyEventQuery);
  });

  it('should have the property filter (base name: "filter")', function() {
    // uncomment below and update the code to test the property filter
    //var instance = new SquareConnect.LoyaltyEventQuery();
    //expect(instance).to.be();
  });
});
