/**
 * Square Connect API
 * Client library for accessing the Square Connect APIs
 *
 * OpenAPI spec version: 2.0
 * Contact: developers@squareup.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.3.0-SNAPSHOT
 *
 */
const SquareConnect = require('../../src/index');

describe('LoyaltyEventDeleteReward', function() {
  beforeEach(function() {
    this.api = new SquareConnect.LoyaltyEventDeleteReward();
  });

  it('should create an instance of LoyaltyEventDeleteReward', function() {
    // uncomment below and update the code to test LoyaltyEventDeleteReward
    //var instane = new SquareConnect.LoyaltyEventDeleteReward();
    //expect(instance).to.be.a(SquareConnect.LoyaltyEventDeleteReward);
  });

  it('should have the property loyaltyProgramId (base name: "loyalty_program_id")', function() {
    // uncomment below and update the code to test the property loyaltyProgramId
    //var instane = new SquareConnect.LoyaltyEventDeleteReward();
    //expect(instance).to.be();
  });
  it('should have the property rewardId (base name: "reward_id")', function() {
    // uncomment below and update the code to test the property rewardId
    //var instane = new SquareConnect.LoyaltyEventDeleteReward();
    //expect(instance).to.be();
  });
  it('should have the property points (base name: "points")', function() {
    // uncomment below and update the code to test the property points
    //var instane = new SquareConnect.LoyaltyEventDeleteReward();
    //expect(instance).to.be();
  });
});
