/**
 * Square Connect API
 * Client library for accessing the Square Connect APIs
 *
 * OpenAPI spec version: 2.0
 * Contact: developers@squareup.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.3.0-SNAPSHOT
 *
 */
const SquareConnect = require('../../src/index');

describe('OrderPricingOptions', function() {
  beforeEach(function() {
    this.api = new SquareConnect.OrderPricingOptions();
  });

  it('should create an instance of OrderPricingOptions', function() {
    // uncomment below and update the code to test OrderPricingOptions
    //var instance = new SquareConnect.OrderPricingOptions();
    //expect(instance).to.be.a(SquareConnect.OrderPricingOptions);
  });

  it('should have the property autoApplyDiscounts (base name: "auto_apply_discounts")', function() {
    // uncomment below and update the code to test the property autoApplyDiscounts
    //var instance = new SquareConnect.OrderPricingOptions();
    //expect(instance).to.be();
  });
});
