/**
 * Square Connect API
 * Client library for accessing the Square Connect APIs
 *
 * OpenAPI spec version: 2.0
 * Contact: developers@squareup.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.20191217.0-SNAPSHOT
 *
 */
const SquareConnect = require('../../src/index');

describe('OrderFulfillmentShipmentDetails', function() {
  beforeEach(function() {
    this.api = new SquareConnect.OrderFulfillmentShipmentDetails();
  });

  it('should create an instance of OrderFulfillmentShipmentDetails', function() {
    // uncomment below and update the code to test OrderFulfillmentShipmentDetails
    //var instane = new SquareConnect.OrderFulfillmentShipmentDetails();
    //expect(instance).to.be.a(SquareConnect.OrderFulfillmentShipmentDetails);
  });

  it('should have the property recipient (base name: "recipient")', function() {
    // uncomment below and update the code to test the property recipient
    //var instane = new SquareConnect.OrderFulfillmentShipmentDetails();
    //expect(instance).to.be();
  });
  it('should have the property carrier (base name: "carrier")', function() {
    // uncomment below and update the code to test the property carrier
    //var instane = new SquareConnect.OrderFulfillmentShipmentDetails();
    //expect(instance).to.be();
  });
  it('should have the property shippingNote (base name: "shipping_note")', function() {
    // uncomment below and update the code to test the property shippingNote
    //var instane = new SquareConnect.OrderFulfillmentShipmentDetails();
    //expect(instance).to.be();
  });
  it('should have the property shippingType (base name: "shipping_type")', function() {
    // uncomment below and update the code to test the property shippingType
    //var instane = new SquareConnect.OrderFulfillmentShipmentDetails();
    //expect(instance).to.be();
  });
  it('should have the property trackingNumber (base name: "tracking_number")', function() {
    // uncomment below and update the code to test the property trackingNumber
    //var instane = new SquareConnect.OrderFulfillmentShipmentDetails();
    //expect(instance).to.be();
  });
  it('should have the property trackingUrl (base name: "tracking_url")', function() {
    // uncomment below and update the code to test the property trackingUrl
    //var instane = new SquareConnect.OrderFulfillmentShipmentDetails();
    //expect(instance).to.be();
  });
  it('should have the property placedAt (base name: "placed_at")', function() {
    // uncomment below and update the code to test the property placedAt
    //var instane = new SquareConnect.OrderFulfillmentShipmentDetails();
    //expect(instance).to.be();
  });
  it('should have the property inProgressAt (base name: "in_progress_at")', function() {
    // uncomment below and update the code to test the property inProgressAt
    //var instane = new SquareConnect.OrderFulfillmentShipmentDetails();
    //expect(instance).to.be();
  });
  it('should have the property packagedAt (base name: "packaged_at")', function() {
    // uncomment below and update the code to test the property packagedAt
    //var instane = new SquareConnect.OrderFulfillmentShipmentDetails();
    //expect(instance).to.be();
  });
  it('should have the property expectedShippedAt (base name: "expected_shipped_at")', function() {
    // uncomment below and update the code to test the property expectedShippedAt
    //var instane = new SquareConnect.OrderFulfillmentShipmentDetails();
    //expect(instance).to.be();
  });
  it('should have the property shippedAt (base name: "shipped_at")', function() {
    // uncomment below and update the code to test the property shippedAt
    //var instane = new SquareConnect.OrderFulfillmentShipmentDetails();
    //expect(instance).to.be();
  });
  it('should have the property canceledAt (base name: "canceled_at")', function() {
    // uncomment below and update the code to test the property canceledAt
    //var instane = new SquareConnect.OrderFulfillmentShipmentDetails();
    //expect(instance).to.be();
  });
  it('should have the property cancelReason (base name: "cancel_reason")', function() {
    // uncomment below and update the code to test the property cancelReason
    //var instane = new SquareConnect.OrderFulfillmentShipmentDetails();
    //expect(instance).to.be();
  });
  it('should have the property failedAt (base name: "failed_at")', function() {
    // uncomment below and update the code to test the property failedAt
    //var instane = new SquareConnect.OrderFulfillmentShipmentDetails();
    //expect(instance).to.be();
  });
  it('should have the property failureReason (base name: "failure_reason")', function() {
    // uncomment below and update the code to test the property failureReason
    //var instane = new SquareConnect.OrderFulfillmentShipmentDetails();
    //expect(instance).to.be();
  });
});
