/**
 * Square Connect API
 * Client library for accessing the Square Connect APIs
 *
 * OpenAPI spec version: 2.0
 * Contact: developers@squareup.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.3.0-SNAPSHOT
 *
 */
const SquareConnect = require('../../src/index');

describe('PaymentRefund', function() {
  beforeEach(function() {
    this.api = new SquareConnect.PaymentRefund();
  });

  it('should create an instance of PaymentRefund', function() {
    // uncomment below and update the code to test PaymentRefund
    //var instance = new SquareConnect.PaymentRefund();
    //expect(instance).to.be.a(SquareConnect.PaymentRefund);
  });

  it('should have the property id (base name: "id")', function() {
    // uncomment below and update the code to test the property id
    //var instance = new SquareConnect.PaymentRefund();
    //expect(instance).to.be();
  });
  it('should have the property status (base name: "status")', function() {
    // uncomment below and update the code to test the property status
    //var instance = new SquareConnect.PaymentRefund();
    //expect(instance).to.be();
  });
  it('should have the property locationId (base name: "location_id")', function() {
    // uncomment below and update the code to test the property locationId
    //var instance = new SquareConnect.PaymentRefund();
    //expect(instance).to.be();
  });
  it('should have the property amountMoney (base name: "amount_money")', function() {
    // uncomment below and update the code to test the property amountMoney
    //var instance = new SquareConnect.PaymentRefund();
    //expect(instance).to.be();
  });
  it('should have the property appFeeMoney (base name: "app_fee_money")', function() {
    // uncomment below and update the code to test the property appFeeMoney
    //var instance = new SquareConnect.PaymentRefund();
    //expect(instance).to.be();
  });
  it('should have the property processingFee (base name: "processing_fee")', function() {
    // uncomment below and update the code to test the property processingFee
    //var instance = new SquareConnect.PaymentRefund();
    //expect(instance).to.be();
  });
  it('should have the property paymentId (base name: "payment_id")', function() {
    // uncomment below and update the code to test the property paymentId
    //var instance = new SquareConnect.PaymentRefund();
    //expect(instance).to.be();
  });
  it('should have the property reason (base name: "reason")', function() {
    // uncomment below and update the code to test the property reason
    //var instance = new SquareConnect.PaymentRefund();
    //expect(instance).to.be();
  });
  it('should have the property createdAt (base name: "created_at")', function() {
    // uncomment below and update the code to test the property createdAt
    //var instance = new SquareConnect.PaymentRefund();
    //expect(instance).to.be();
  });
  it('should have the property updatedAt (base name: "updated_at")', function() {
    // uncomment below and update the code to test the property updatedAt
    //var instance = new SquareConnect.PaymentRefund();
    //expect(instance).to.be();
  });
});
