/**
 * Square Connect API
 * Client library for accessing the Square Connect APIs
 *
 * OpenAPI spec version: 2.0
 * Contact: developers@squareup.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.3.0-SNAPSHOT
 *
 */
const SquareConnect = require('../../src/index');

describe('RetrieveTeamMemberResponse', function() {
  beforeEach(function() {
    this.api = new SquareConnect.RetrieveTeamMemberResponse();
  });

  it('should create an instance of RetrieveTeamMemberResponse', function() {
    // uncomment below and update the code to test RetrieveTeamMemberResponse
    //var instane = new SquareConnect.RetrieveTeamMemberResponse();
    //expect(instance).to.be.a(SquareConnect.RetrieveTeamMemberResponse);
  });

  it('should have the property teamMember (base name: "team_member")', function() {
    // uncomment below and update the code to test the property teamMember
    //var instane = new SquareConnect.RetrieveTeamMemberResponse();
    //expect(instance).to.be();
  });
  it('should have the property errors (base name: "errors")', function() {
    // uncomment below and update the code to test the property errors
    //var instane = new SquareConnect.RetrieveTeamMemberResponse();
    //expect(instance).to.be();
  });
});
