/**
 * Square Connect API
 * Client library for accessing the Square Connect APIs
 *
 * OpenAPI spec version: 2.0
 * Contact: developers@squareup.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.3.0-SNAPSHOT
 *
 */
const SquareConnect = require('../../src/index');

describe('RetrieveCustomerGroupResponse', function() {
  beforeEach(function() {
    this.api = new SquareConnect.RetrieveCustomerGroupResponse();
  });

  it('should create an instance of RetrieveCustomerGroupResponse', function() {
    // uncomment below and update the code to test RetrieveCustomerGroupResponse
    //var instane = new SquareConnect.RetrieveCustomerGroupResponse();
    //expect(instance).to.be.a(SquareConnect.RetrieveCustomerGroupResponse);
  });

  it('should have the property errors (base name: "errors")', function() {
    // uncomment below and update the code to test the property errors
    //var instane = new SquareConnect.RetrieveCustomerGroupResponse();
    //expect(instance).to.be();
  });
  it('should have the property group (base name: "group")', function() {
    // uncomment below and update the code to test the property group
    //var instane = new SquareConnect.RetrieveCustomerGroupResponse();
    //expect(instance).to.be();
  });
});
