/**
 * Square Connect API
 * Client library for accessing the Square Connect APIs
 *
 * OpenAPI spec version: 2.0
 * Contact: developers@squareup.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.3.0-SNAPSHOT
 *
 */
const SquareConnect = require('../../src/index');

describe('SearchLoyaltyAccountsRequest', function() {
  beforeEach(function() {
    this.api = new SquareConnect.SearchLoyaltyAccountsRequest();
  });

  it('should create an instance of SearchLoyaltyAccountsRequest', function() {
    // uncomment below and update the code to test SearchLoyaltyAccountsRequest
    //var instane = new SquareConnect.SearchLoyaltyAccountsRequest();
    //expect(instance).to.be.a(SquareConnect.SearchLoyaltyAccountsRequest);
  });

  it('should have the property query (base name: "query")', function() {
    // uncomment below and update the code to test the property query
    //var instane = new SquareConnect.SearchLoyaltyAccountsRequest();
    //expect(instance).to.be();
  });
  it('should have the property limit (base name: "limit")', function() {
    // uncomment below and update the code to test the property limit
    //var instane = new SquareConnect.SearchLoyaltyAccountsRequest();
    //expect(instance).to.be();
  });
  it('should have the property cursor (base name: "cursor")', function() {
    // uncomment below and update the code to test the property cursor
    //var instane = new SquareConnect.SearchLoyaltyAccountsRequest();
    //expect(instance).to.be();
  });
});
