/**
 * Square Connect API
 * Client library for accessing the Square Connect APIs
 *
 * OpenAPI spec version: 2.0
 * Contact: developers@squareup.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.3.0-SNAPSHOT
 *
 */
const SquareConnect = require('../../src/index');

describe('SearchLoyaltyAccountsRequestLoyaltyAccountQuery', function() {
  beforeEach(function() {
    this.api = new SquareConnect.SearchLoyaltyAccountsRequestLoyaltyAccountQuery();
  });

  it('should create an instance of SearchLoyaltyAccountsRequestLoyaltyAccountQuery', function() {
    // uncomment below and update the code to test SearchLoyaltyAccountsRequestLoyaltyAccountQuery
    //var instance = new SquareConnect.SearchLoyaltyAccountsRequestLoyaltyAccountQuery();
    //expect(instance).to.be.a(SquareConnect.SearchLoyaltyAccountsRequestLoyaltyAccountQuery);
  });

  it('should have the property mappings (base name: "mappings")', function() {
    // uncomment below and update the code to test the property mappings
    //var instance = new SquareConnect.SearchLoyaltyAccountsRequestLoyaltyAccountQuery();
    //expect(instance).to.be();
  });
});
