/**
 * Square Connect API
 * Client library for accessing the Square Connect APIs
 *
 * OpenAPI spec version: 2.0
 * Contact: developers@squareup.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.3.0-SNAPSHOT
 *
 */
const SquareConnect = require('../../src/index');

describe('ShiftFilter', function() {
  beforeEach(function() {
    this.api = new SquareConnect.ShiftFilter();
  });

  it('should create an instance of ShiftFilter', function() {
    // uncomment below and update the code to test ShiftFilter
    //var instane = new SquareConnect.ShiftFilter();
    //expect(instance).to.be.a(SquareConnect.ShiftFilter);
  });

  it('should have the property locationId (base name: "location_id")', function() {
    // uncomment below and update the code to test the property locationId
    //var instane = new SquareConnect.ShiftFilter();
    //expect(instance).to.be();
  });
  it('should have the property employeeId (base name: "employee_id")', function() {
    // uncomment below and update the code to test the property employeeId
    //var instane = new SquareConnect.ShiftFilter();
    //expect(instance).to.be();
  });
  it('should have the property status (base name: "status")', function() {
    // uncomment below and update the code to test the property status
    //var instane = new SquareConnect.ShiftFilter();
    //expect(instance).to.be();
  });
  it('should have the property start (base name: "start")', function() {
    // uncomment below and update the code to test the property start
    //var instane = new SquareConnect.ShiftFilter();
    //expect(instance).to.be();
  });
  it('should have the property end (base name: "end")', function() {
    // uncomment below and update the code to test the property end
    //var instane = new SquareConnect.ShiftFilter();
    //expect(instance).to.be();
  });
  it('should have the property workday (base name: "workday")', function() {
    // uncomment below and update the code to test the property workday
    //var instane = new SquareConnect.ShiftFilter();
    //expect(instance).to.be();
  });
});
