/**
 * Square Connect API
 * Client library for accessing the Square Connect APIs
 *
 * OpenAPI spec version: 2.0
 * Contact: developers@squareup.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.3.0-SNAPSHOT
 *
 */
const SquareConnect = require('../../src/index');

describe('Subscription', function() {
  beforeEach(function() {
    this.api = new SquareConnect.Subscription();
  });

  it('should create an instance of Subscription', function() {
    // uncomment below and update the code to test Subscription
    //var instane = new SquareConnect.Subscription();
    //expect(instance).to.be.a(SquareConnect.Subscription);
  });

  it('should have the property id (base name: "id")', function() {
    // uncomment below and update the code to test the property id
    //var instane = new SquareConnect.Subscription();
    //expect(instance).to.be();
  });
  it('should have the property locationId (base name: "location_id")', function() {
    // uncomment below and update the code to test the property locationId
    //var instane = new SquareConnect.Subscription();
    //expect(instance).to.be();
  });
  it('should have the property planId (base name: "plan_id")', function() {
    // uncomment below and update the code to test the property planId
    //var instane = new SquareConnect.Subscription();
    //expect(instance).to.be();
  });
  it('should have the property customerId (base name: "customer_id")', function() {
    // uncomment below and update the code to test the property customerId
    //var instane = new SquareConnect.Subscription();
    //expect(instance).to.be();
  });
  it('should have the property startDate (base name: "start_date")', function() {
    // uncomment below and update the code to test the property startDate
    //var instane = new SquareConnect.Subscription();
    //expect(instance).to.be();
  });
  it('should have the property canceledDate (base name: "canceled_date")', function() {
    // uncomment below and update the code to test the property canceledDate
    //var instane = new SquareConnect.Subscription();
    //expect(instance).to.be();
  });
  it('should have the property status (base name: "status")', function() {
    // uncomment below and update the code to test the property status
    //var instane = new SquareConnect.Subscription();
    //expect(instance).to.be();
  });
  it('should have the property taxPercentage (base name: "tax_percentage")', function() {
    // uncomment below and update the code to test the property taxPercentage
    //var instane = new SquareConnect.Subscription();
    //expect(instance).to.be();
  });
  it('should have the property invoiceIds (base name: "invoice_ids")', function() {
    // uncomment below and update the code to test the property invoiceIds
    //var instane = new SquareConnect.Subscription();
    //expect(instance).to.be();
  });
  it('should have the property priceOverrideMoney (base name: "price_override_money")', function() {
    // uncomment below and update the code to test the property priceOverrideMoney
    //var instane = new SquareConnect.Subscription();
    //expect(instance).to.be();
  });
  it('should have the property version (base name: "version")', function() {
    // uncomment below and update the code to test the property version
    //var instane = new SquareConnect.Subscription();
    //expect(instance).to.be();
  });
  it('should have the property createdAt (base name: "created_at")', function() {
    // uncomment below and update the code to test the property createdAt
    //var instane = new SquareConnect.Subscription();
    //expect(instance).to.be();
  });
  it('should have the property cardId (base name: "card_id")', function() {
    // uncomment below and update the code to test the property cardId
    //var instane = new SquareConnect.Subscription();
    //expect(instance).to.be();
  });
  it('should have the property paidUntilDate (base name: "paid_until_date")', function() {
    // uncomment below and update the code to test the property paidUntilDate
    //var instane = new SquareConnect.Subscription();
    //expect(instance).to.be();
  });
  it('should have the property timezone (base name: "timezone")', function() {
    // uncomment below and update the code to test the property timezone
    //var instane = new SquareConnect.Subscription();
    //expect(instance).to.be();
  });
});
