/**
 * Square Connect API
 * Client library for accessing the Square Connect APIs
 *
 * OpenAPI spec version: 2.0
 * Contact: developers@squareup.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.3.0-SNAPSHOT
 *
 */
const SquareConnect = require('../../src/index');

describe('UpdateInvoiceResponse', function() {
  beforeEach(function() {
    this.api = new SquareConnect.UpdateInvoiceResponse();
  });

  it('should create an instance of UpdateInvoiceResponse', function() {
    // uncomment below and update the code to test UpdateInvoiceResponse
    //var instance = new SquareConnect.UpdateInvoiceResponse();
    //expect(instance).to.be.a(SquareConnect.UpdateInvoiceResponse);
  });

  it('should have the property invoice (base name: "invoice")', function() {
    // uncomment below and update the code to test the property invoice
    //var instance = new SquareConnect.UpdateInvoiceResponse();
    //expect(instance).to.be();
  });
  it('should have the property errors (base name: "errors")', function() {
    // uncomment below and update the code to test the property errors
    //var instance = new SquareConnect.UpdateInvoiceResponse();
    //expect(instance).to.be();
  });
});
