/**
 * Square Connect API
 * Client library for accessing the Square Connect APIs
 *
 * OpenAPI spec version: 2.0
 * Contact: developers@squareup.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.20191217.0-SNAPSHOT
 *
 */
const SquareConnect = require('../../src/index');

describe('V1DeleteModifierListRequest', function() {
  beforeEach(function() {
    this.api = new SquareConnect.V1DeleteModifierListRequest();
  });

  it('should create an instance of V1DeleteModifierListRequest', function() {
    // uncomment below and update the code to test V1DeleteModifierListRequest
    //var instane = new SquareConnect.V1DeleteModifierListRequest();
    //expect(instance).to.be.a(SquareConnect.V1DeleteModifierListRequest);
  });

});
