/**
 * Square Connect API
 * Client library for accessing the Square Connect APIs
 *
 * OpenAPI spec version: 2.0
 * Contact: developers@squareup.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.3.0-SNAPSHOT
 *
 */

const SquareConnect = require('../../src/index');

describe('V1Discount', function() {
  beforeEach(function() {
    this.api = new SquareConnect.V1Discount();
  });

  it('should create an instance of V1Discount', function() {
    // uncomment below and update the code to test V1Discount
    //var instance = new SquareConnect.V1Discount();
    //expect(instance).to.be.a(SquareConnect.V1Discount);
  });

  it('should have the property id (base name: "id")', function() {
    // uncomment below and update the code to test the property id
    //var instance = new SquareConnect.V1Discount();
    //expect(instance).to.be();
  });
  it('should have the property name (base name: "name")', function() {
    // uncomment below and update the code to test the property name
    //var instance = new SquareConnect.V1Discount();
    //expect(instance).to.be();
  });
  it('should have the property rate (base name: "rate")', function() {
    // uncomment below and update the code to test the property rate
    //var instance = new SquareConnect.V1Discount();
    //expect(instance).to.be();
  });
  it('should have the property amountMoney (base name: "amount_money")', function() {
    // uncomment below and update the code to test the property amountMoney
    //var instance = new SquareConnect.V1Discount();
    //expect(instance).to.be();
  });
  it('should have the property discountType (base name: "discount_type")', function() {
    // uncomment below and update the code to test the property discountType
    //var instance = new SquareConnect.V1Discount();
    //expect(instance).to.be();
  });
  it('should have the property pinRequired (base name: "pin_required")', function() {
    // uncomment below and update the code to test the property pinRequired
    //var instance = new SquareConnect.V1Discount();
    //expect(instance).to.be();
  });
  it('should have the property color (base name: "color")', function() {
    // uncomment below and update the code to test the property color
    //var instance = new SquareConnect.V1Discount();
    //expect(instance).to.be();
  });
});

