/**
 * Square Connect API
 * Client library for accessing the Square Connect APIs
 *
 * OpenAPI spec version: 2.0
 * Contact: developers@squareup.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.3.0-SNAPSHOT
 *
 */

const SquareConnect = require('../../src/index');

describe('V1InventoryEntry', function() {
  beforeEach(function() {
    this.api = new SquareConnect.V1InventoryEntry();
  });

  it('should create an instance of V1InventoryEntry', function() {
    // uncomment below and update the code to test V1InventoryEntry
    //var instance = new SquareConnect.V1InventoryEntry();
    //expect(instance).to.be.a(SquareConnect.V1InventoryEntry);
  });

  it('should have the property variationId (base name: "variation_id")', function() {
    // uncomment below and update the code to test the property variationId
    //var instance = new SquareConnect.V1InventoryEntry();
    //expect(instance).to.be();
  });
  it('should have the property quantityOnHand (base name: "quantity_on_hand")', function() {
    // uncomment below and update the code to test the property quantityOnHand
    //var instance = new SquareConnect.V1InventoryEntry();
    //expect(instance).to.be();
  });
});

