/**
 * Square Connect API
 * Client library for accessing the Square Connect APIs
 *
 * OpenAPI spec version: 2.0
 * Contact: developers@squareup.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.20191217.0-SNAPSHOT
 *
 */
const SquareConnect = require('../../src/index');

describe('V1ListRefundsResponse', function() {
  beforeEach(function() {
    this.api = new SquareConnect.V1ListRefundsResponse();
  });

  it('should create an instance of V1ListRefundsResponse', function() {
    // uncomment below and update the code to test V1ListRefundsResponse
    //var instane = new SquareConnect.V1ListRefundsResponse();
    //expect(instance).to.be.a(SquareConnect.V1ListRefundsResponse);
  });

  it('should have the property items (base name: "items")', function() {
    // uncomment below and update the code to test the property items
    //var instane = new SquareConnect.V1ListRefundsResponse();
    //expect(instance).to.be();
  });
});
