/**
 * Square Connect API
 * Client library for accessing the Square Connect APIs
 *
 * OpenAPI spec version: 2.0
 * Contact: developers@squareup.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.3.0-SNAPSHOT
 *
 */

const SquareConnect = require('../../src/index');

describe('V1SettlementEntry', function() {
  beforeEach(function() {
    this.api = new SquareConnect.V1SettlementEntry();
  });

  it('should create an instance of V1SettlementEntry', function() {
    // uncomment below and update the code to test V1SettlementEntry
    //var instance = new SquareConnect.V1SettlementEntry();
    //expect(instance).to.be.a(SquareConnect.V1SettlementEntry);
  });

  it('should have the property paymentId (base name: "payment_id")', function() {
    // uncomment below and update the code to test the property paymentId
    //var instance = new SquareConnect.V1SettlementEntry();
    //expect(instance).to.be();
  });
  it('should have the property type (base name: "type")', function() {
    // uncomment below and update the code to test the property type
    //var instance = new SquareConnect.V1SettlementEntry();
    //expect(instance).to.be();
  });
  it('should have the property amountMoney (base name: "amount_money")', function() {
    // uncomment below and update the code to test the property amountMoney
    //var instance = new SquareConnect.V1SettlementEntry();
    //expect(instance).to.be();
  });
  it('should have the property feeMoney (base name: "fee_money")', function() {
    // uncomment below and update the code to test the property feeMoney
    //var instance = new SquareConnect.V1SettlementEntry();
    //expect(instance).to.be();
  });
});

