/**
 * Square Connect API
 * Client library for accessing the Square Connect APIs
 *
 * OpenAPI spec version: 2.0
 * Contact: developers@squareup.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.3.0-SNAPSHOT
 *
 */
const SquareConnect = require('../../src/index');

describe('VersionedCatalogObject', function() {
  beforeEach(function() {
    // this.api = new SquareConnect.VersionedCatalogObject();
  });

  it('should create an instance of VersionedCatalogObject', function() {
    // uncomment below and update the code to test VersionedCatalogObject
    //var instane = new SquareConnect.VersionedCatalogObject();
    //expect(instance).to.be.a(SquareConnect.VersionedCatalogObject);
  });

  it('should have the property objectId (base name: "object_id")', function() {
    // uncomment below and update the code to test the property objectId
    //var instane = new SquareConnect.VersionedCatalogObject();
    //expect(instance).to.be();
  });
  it('should have the property catalogVersion (base name: "catalog_version")', function() {
    // uncomment below and update the code to test the property catalogVersion
    //var instane = new SquareConnect.VersionedCatalogObject();
    //expect(instance).to.be();
  });
});
