const SquareConnect = require('../../src/index');
const {
  accounts,
  expect,
  handleUnexpectedError
} = require('../support/setup');

/**
 * Square Connect API
 * Client library for accessing the Square Connect APIs
 *
 * OpenAPI spec version: 2.0
 * Contact: developers@squareup.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.20191217.0-SNAPSHOT
 *
 */

describe('CashDrawersApi', function() {
  beforeEach(function() {
    const defaultClient = SquareConnect.ApiClient.instance;
    const oauth2 = defaultClient.authentications['oauth2'];
    // Some APIs do not work with sandbox. Replace `sandbox` with `production` for those test suites.
    oauth2.accessToken = accounts.sandbox.access_token;
    this.api  = new SquareConnect.CashDrawersApi();
  });

  afterEach(function(){
  });

  describe('CashDrawersApi', function() {
    describe('listCashDrawerShiftEvents', function() {
      it('should call listCashDrawerShiftEvents successfully', function(done) {
        //uncomment below and update the code to test listCashDrawerShiftEvents
        //instance.listCashDrawerShiftEvents(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('listCashDrawerShifts', function() {
      it('should call listCashDrawerShifts successfully', function(done) {
        //uncomment below and update the code to test listCashDrawerShifts
        //instance.listCashDrawerShifts(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('retrieveCashDrawerShift', function() {
      it('should call retrieveCashDrawerShift successfully', function(done) {
        //uncomment below and update the code to test retrieveCashDrawerShift
        //instance.retrieveCashDrawerShift(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
  });
});
