const SquareConnect = require('../../src/index');
const {
  accounts,
  expect,
  handleUnexpectedError
} = require('../support/setup');

/**
 * Square Connect API
 * Client library for accessing the Square Connect APIs
 *
 * OpenAPI spec version: 2.0
 * Contact: developers@squareup.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.3.0-SNAPSHOT
 *
 */

describe('TeamApi', function() {
  beforeEach(function() {
    const defaultClient = SquareConnect.ApiClient.instance;
    const oauth2 = defaultClient.authentications['oauth2'];
    // Some APIs do not work with sandbox. Replace `sandbox` with `production` for those test suites.
    oauth2.accessToken = accounts.sandbox.access_token;
    this.api  = new SquareConnect.TeamApi();
  });

  afterEach(function(){
  });

  describe('TeamApi', function() {
    describe('bulkCreateTeamMembers', function() {
      it('should call bulkCreateTeamMembers successfully', function(done) {
        //uncomment below and update the code to test bulkCreateTeamMembers
        //instance.bulkCreateTeamMembers(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('bulkUpdateTeamMembers', function() {
      it('should call bulkUpdateTeamMembers successfully', function(done) {
        //uncomment below and update the code to test bulkUpdateTeamMembers
        //instance.bulkUpdateTeamMembers(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('createTeamMember', function() {
      it('should call createTeamMember successfully', function(done) {
        //uncomment below and update the code to test createTeamMember
        //instance.createTeamMember(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('retrieveTeamMember', function() {
      it('should call retrieveTeamMember successfully', function(done) {
        //uncomment below and update the code to test retrieveTeamMember
        //instance.retrieveTeamMember(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('retrieveWageSetting', function() {
      it('should call retrieveWageSetting successfully', function(done) {
        //uncomment below and update the code to test retrieveWageSetting
        //instance.retrieveWageSetting(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('searchTeamMembers', function() {
      it('should call searchTeamMembers successfully', function(done) {
        //uncomment below and update the code to test searchTeamMembers
        //instance.searchTeamMembers(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('updateTeamMember', function() {
      it('should call updateTeamMember successfully', function(done) {
        //uncomment below and update the code to test updateTeamMember
        //instance.updateTeamMember(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('updateWageSetting', function() {
      it('should call updateWageSetting successfully', function(done) {
        //uncomment below and update the code to test updateWageSetting
        //instance.updateWageSetting(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
  });
});
